"""Initial migration.

Revision ID: 6dde783d09a0
Revises: 
Create Date: 2021-07-30 22:44:34.226587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dde783d09a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortner_tb', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shortner_tb', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortner_tb', 'generated_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shortner_tb', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
